### ISSUE TITLE
Support for imports from deno libraries

### ISSUE THREAD

**Issue by alqubo** [pagoru/deno-web-serve#1]
Si se tienen en el código imports de otros módulos, no se procesan y salta error a la hora de ejecutarlo.

![image](https://github.com/pagoru/deno-web-serve/assets/9885515/30bf4c52-e597-4212-addc-3ab531e6cc02)

Código
![image](https://github.com/pagoru/deno-web-serve/assets/9885515/32ae525d-5266-4da2-81de-428448eebf7c)

En el fichero bundle.js generado:
![image](https://github.com/pagoru/deno-web-serve/assets/9885515/95272fd9-4308-477c-a124-b102bbe1042d)

**Comment by pagoru** [comment]
Está realmente pensado para que opere en front, asi que no lo he testeado para que opere con imports externos de ningun tipo (ni tampoco node) que es algo que webpack se come e inserta en el codigo. Quizá estaria guay implementarlo, pero lo vi muy complicado y desistí 👯
